#!/bin/bash

origaddr=$1
origaddrlen=${#origaddr}
template="0000"
templatelen=${#template}

if [ $origaddrlen -gt $templatelen ]; then
	echo "format-address : ERROR (the string is to long)."
	MMIX-RETURN $0 "ERROR"
	exit 0
fi

to=`expr $(($templatelen-$origaddrlen))`
if [ $to -eq 0 ]; then
	echo $origaddr
	MMIX-RETURN $0 "ERROR"
	exit 0
fi

addr=`echo $template | cut -c 1-$to | sed -e 's/$/'"$origaddr"'/g'`
MMIX-RETURN $0 $addr


