#!/bin/bash

sign=$1
rIIdx=$2
AA=$3

if [ $rIIdx -eq 00 ]; then
	MMIX-RETURN $0 $AA
	exit 0
fi

#Get the I$I register contents
rIx4=`cat $CPU_REG_BASE/I$rIIdx/I${rIIdx}4`
rIx5=`cat $CPU_REG_BASE/I$rIIdx/I${rIIdx}5`
rflg=`cat $CPU_REG_BASE/I$rIIdx/flag`

#ignore the flag temprority.
Ival=$rIx4$rIx5

if [ $sign -eq 00 ]; then
	addr=`expr $(($((num=16#${Ival}))+${AA}))`
else
	addr=`expr $(($((num=16#${Ival}))-${AA}))`
fi

MMIX-RETURN $0 `echo "obase=16;${addr}"|bc`

